import { buildPublicPracticeQuestions } from './public-practice-question-builders';
import {
  BUSINESS_DELIVERY_QUESTION_INPUTS,
  GENERIC_QUESTION_INPUTS,
} from './public-practice-questions-business';

export const PUBLIC_PRACTICE_QUESTIONS = [
  ...buildPublicPracticeQuestions('engineering', [
    {
      suffix: 'engineering-boundary',
      title: '如何划分订单系统的模块边界？',
      stem: '请说明订单、库存、支付之间的职责边界、数据一致性策略和失败处理方式。',
      answer: '先明确系统边界与职责，再通过事件、幂等和补偿机制处理一致性与失败恢复。',
      tags: ['系统设计', '订单'],
      points: ['系统边界', '一致性策略', '失败恢复'],
    },
    {
      suffix: 'engineering-performance',
      title: '如何推进一次接口性能优化？',
      stem: '请说明你会如何定位瓶颈、选择优化方案，并验证优化收益与回归风险。',
      answer: '从监控和压测定位瓶颈，结合缓存、索引或异步化做技术取舍，并以指标和回归测试验证。',
      tags: ['性能优化', '可观测性'],
      points: ['瓶颈定位', '技术取舍', '指标验证'],
    },
    {
      suffix: 'engineering-stability',
      title: '线上核心服务出现故障时如何处理？',
      stem: '请说明告警响应、止损、根因定位、恢复验证和后续治理的完整过程。',
      answer: '先止损并保障用户，再基于日志和监控定位根因，验证恢复后补齐预案与治理项。',
      tags: ['稳定性', '故障治理'],
      points: ['快速止损', '根因定位', '治理闭环'],
    },
    {
      suffix: 'engineering-quality',
      title: '如何为高风险发布建立质量保障？',
      stem: '请结合真实项目说明测试策略、发布方案、灰度指标和回滚条件。',
      answer: '通过分层测试、灰度发布、核心指标监控和明确回滚阈值降低上线风险。',
      tags: ['工程质量', '发布'],
      points: ['测试策略', '灰度验证', '回滚条件'],
    },
    {
      suffix: 'engineering-delivery',
      title: '如何与产品和设计协作推进复杂需求？',
      stem: '请说明你如何澄清约束、拆解交付、同步风险并完成验收。',
      answer: '在需求评审明确约束和边界，拆分可验证交付，并持续同步风险和验收标准。',
      tags: ['协作交付', '需求管理'],
      points: ['约束澄清', '交付拆解', '结果验收'],
    },
  ]),
  ...buildPublicPracticeQuestions('data', [
    {
      suffix: 'data-metric',
      title: '如何定义一个增长指标的口径？',
      stem: '请说明指标目标、计算范围、数据来源、异常处理以及与业务团队的对齐方式。',
      answer: '先对齐业务目标，再定义口径、数据来源和异常规则，并通过评审确保可复用。',
      tags: ['指标体系', '业务分析'],
      points: ['业务目标', '指标口径', '对齐机制'],
    },
    {
      suffix: 'data-quality',
      title: '发现核心报表数据异常时如何处理？',
      stem: '请说明你如何排查数据链路、判断影响范围并恢复业务决策可信度。',
      answer: '沿采集、加工和消费链路排查，量化影响范围，修复后补齐数据质量监控和说明。',
      tags: ['数据质量', '数据治理'],
      points: ['链路排查', '影响评估', '质量治理'],
    },
    {
      suffix: 'data-experiment',
      title: '如何设计一次 A/B 实验？',
      stem: '请说明假设、分流、样本量、核心指标、风险指标和结论判定方式。',
      answer: '围绕可验证假设设计随机分流和样本量，以核心与护栏指标共同判断实验结论。',
      tags: ['实验设计', 'A/B 测试'],
      points: ['实验假设', '指标设计', '结论判定'],
    },
    {
      suffix: 'data-method',
      title: '如何选择分析方法或预测模型？',
      stem: '请说明你如何在可解释性、准确性、时效性和成本之间做取舍。',
      answer: '先明确业务决策场景，再比较方法在准确性、可解释性、时效性和成本上的边界。',
      tags: ['方法选择', '建模'],
      points: ['场景匹配', '方法取舍', '效果评估'],
    },
    {
      suffix: 'data-insight',
      title: '如何让分析洞察真正推动业务行动？',
      stem: '请说明从发现问题到推动策略落地、验证结果和复盘沉淀的过程。',
      answer: '把洞察转化为明确策略和负责人，用后续指标验证效果，并沉淀为可复用的方法。',
      tags: ['洞察落地', '业务协同'],
      points: ['问题洞察', '行动方案', '效果复盘'],
    },
  ]),
  ...buildPublicPracticeQuestions('ai_agent', [
    {
      suffix: 'agent-workflow',
      title: '如何设计一个多步骤 Agent 工作流？',
      stem: '请说明任务拆解、状态管理、工具调用边界、人工兜底和失败恢复。',
      answer: '将任务拆成显式状态和节点，限制工具权限，为失败设置重试、兜底与人工接管。',
      tags: ['Agent 工作流', '状态管理'],
      points: ['任务拆解', '工具边界', '失败恢复'],
    },
    {
      suffix: 'agent-tools',
      title: '如何控制 Agent 的工具调用权限？',
      stem: '请说明身份、数据范围、工具白名单、审计与高风险操作确认。',
      answer: '按身份和租户约束数据范围，使用工具白名单和参数校验，并记录可审计的调用链路。',
      tags: ['工具权限', '安全'],
      points: ['权限范围', '参数校验', '审计追踪'],
    },
    {
      suffix: 'agent-evaluation',
      title: '如何评估一个 Agent 功能是否可上线？',
      stem: '请说明离线集、线上指标、失败样本、人工评审和版本回归策略。',
      answer: '用代表性离线集和线上业务指标评估效果，持续分析失败样本并做版本回归。',
      tags: ['模型评估', '可观测性'],
      points: ['评估集', '线上指标', '失败分析'],
    },
    {
      suffix: 'agent-cost',
      title: '如何优化 Agent 的响应成本与时延？',
      stem: '请说明你会从模型选择、上下文、缓存、并发和工具调用哪些方面进行优化。',
      answer: '根据任务难度选择模型，控制上下文和缓存命中，并监控并发与工具调用的成本和时延。',
      tags: ['成本优化', '性能'],
      points: ['模型取舍', '上下文治理', '成本监控'],
    },
    {
      suffix: 'agent-recovery',
      title: 'Agent 给出错误结果时如何设计恢复机制？',
      stem: '请说明错误分类、重试条件、降级回答、人工接管和问题沉淀。',
      answer: '先区分可重试与不可重试错误，设计降级和人工接管，并把失败样本反馈到评估与改进。',
      tags: ['失败恢复', '可靠性'],
      points: ['错误分类', '降级策略', '问题沉淀'],
    },
  ]),
  ...buildPublicPracticeQuestions('product_design', [
    {
      suffix: 'product-insight',
      title: '如何从用户反馈中发现真正的问题？',
      stem: '请说明你如何区分表层诉求与根因，并验证问题的普遍性和业务价值。',
      answer: '结合定性访谈和行为数据识别根因，评估人群规模和业务价值后再进入方案设计。',
      tags: ['用户洞察', '需求分析'],
      points: ['问题根因', '用户验证', '业务价值'],
    },
    {
      suffix: 'product-priority',
      title: '如何为需求确定优先级？',
      stem: '请说明你会如何综合用户价值、业务目标、实现成本、风险与时机做判断。',
      answer: '以用户与业务价值为主线，结合成本、风险和时机建立透明的优先级判断。',
      tags: ['优先级', '需求管理'],
      points: ['价值判断', '成本风险', '决策透明'],
    },
    {
      suffix: 'product-tradeoff',
      title: '如何在多个产品方案之间做取舍？',
      stem: '请说明你如何比较方案、识别关键假设、协调团队并选择最小可行路径。',
      answer: '明确关键假设和成功指标，比较方案成本与风险，选择可快速验证的最小可行路径。',
      tags: ['方案取舍', 'MVP'],
      points: ['关键假设', '方案比较', '验证路径'],
    },
    {
      suffix: 'product-rollout',
      title: '新功能上线后如何判断是否成功？',
      stem: '请说明目标指标、用户行为、护栏指标、灰度策略和后续迭代方式。',
      answer: '在上线前定义目标和护栏指标，灰度观察用户行为，再根据数据决定扩大、迭代或回退。',
      tags: ['上线复盘', '产品指标'],
      points: ['目标指标', '护栏指标', '迭代决策'],
    },
    {
      suffix: 'product-collaboration',
      title: '产品方案遇到研发或设计分歧时如何推进？',
      stem: '请说明你如何回到用户价值、澄清约束、达成决策并保障执行。',
      answer: '回到用户价值和业务目标，澄清约束与证据，通过共同决策记录推动后续执行。',
      tags: ['跨团队协作', '沟通'],
      points: ['共同目标', '约束澄清', '执行对齐'],
    },
  ]),
  ...buildPublicPracticeQuestions('growth_operations', [
    {
      suffix: 'growth-segmentation',
      title: '如何为增长项目做用户分层？',
      stem: '请说明分层依据、目标人群、差异化策略、触达节奏和效果验证。',
      answer: '基于生命周期、行为和价值分层，为重点人群设计差异化策略并持续验证转化效果。',
      tags: ['用户分层', '增长'],
      points: ['分层依据', '策略匹配', '效果验证'],
    },
    {
      suffix: 'growth-funnel',
      title: '转化漏斗下降时如何定位问题？',
      stem: '请说明你会如何拆解漏斗、找到异常环节、形成假设并推动修复。',
      answer: '按链路拆分漏斗和人群，定位异常环节，形成可验证假设并通过实验或优化修复。',
      tags: ['漏斗分析', '转化'],
      points: ['链路拆解', '问题定位', '验证修复'],
    },
    {
      suffix: 'growth-experiment',
      title: '如何设计一次运营增长实验？',
      stem: '请说明实验目标、人群、策略变量、指标、样本与风险控制。',
      answer: '围绕明确目标设置人群和变量，结合核心与风险指标控制实验质量。',
      tags: ['运营实验', '策略'],
      points: ['实验目标', '变量设计', '风险控制'],
    },
    {
      suffix: 'growth-roi',
      title: '如何评估渠道投放的投入产出？',
      stem: '请说明归因口径、转化质量、边际成本、长期价值和预算调整。',
      answer: '统一归因口径，结合转化质量和长期价值分析边际成本，再动态调整预算。',
      tags: ['投放优化', 'ROI'],
      points: ['归因口径', '转化质量', '预算决策'],
    },
    {
      suffix: 'growth-review',
      title: '如何复盘一次未达标的运营活动？',
      stem: '请说明目标基线、策略执行、数据结果、问题归因和下一轮动作。',
      answer: '对比目标基线和实际结果，区分策略、渠道和执行问题，并产出下一轮可验证动作。',
      tags: ['运营复盘', '经营结果'],
      points: ['目标基线', '问题归因', '下一步行动'],
    },
  ]),
  ...buildPublicPracticeQuestions('business_delivery', BUSINESS_DELIVERY_QUESTION_INPUTS),
  ...buildPublicPracticeQuestions('generic', GENERIC_QUESTION_INPUTS),
];
